### PR TITLE
Add support for MS-CHAPv2 and MPPE

### PR DESCRIPTION
**Pull request by zonque**
* Add generated code for Microsoft extensions to the CHAP protocol family, using the dictionary from Freeradius.
* Add implementations for some functions described in rfc2759 and rfc3079
* Change handling of the `salt` parameter of `NewTunnelPassword`

With these patches, it is possible to handle requests from clients that use the MS-CHAPv2 protocol and that expect Send/Recv MPPE keys. One such device is the Unify Security Gateway (USG).

### CODE REVIEW

**Comment by zonque** [comment]
I'm not quite sure where to best place this new code, tbh. All other directories prefixed with 'rfc` and all sub-folders of `vendor` contain generated code only, but the new code is very specific to these rfcs. Besides, the code in `vendor/...` also refers to rfcs, so I don't fully understand that distinction.

Please advice in case you want me to change anything.

**Comment by bontibon** [comment]
Thanks for contributing, @zonque. I'll try to review as soon as I can.

**Comment by zonque** [comment]
FWIW, I've now added a some example code to show the usage of that new extension.

**Comment by seglberg** [comment]
Any chance of this getting reviewed soon? We're actually using this PR in a few places for MSCHAPv2 and it has been working well.

**Comment by zonque** [comment]
FWIW, we've now also released a piece of software that depends on it: https://github.com/holoplot/radioauth

**Comment by zonque** [comment]
Friendly reminder. I would much like to avoid this PR bit-rotting.

**Comment by bontibon** [comment]
I've merged your PR into master.  Please give it a test to ensure everything is working as expected.  Thanks!

**Pull request closed without merging**
